spring:
  datasource:
    url: jdbc:h2:tcp://localhost:1522/votes
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
server:
  port: 8081
